schema_version = "1.0.0"
id = "AllPie"
version = "1.0.1"
name = "AllPie"
tagline = "Pie Menus Everywhere"
maintainer = "YAZZ"
type = "add-on"
tags = ["User Interface"]
blender_version_min = "5.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/yazz1482/AllPie"
copyright = ["2026 YAZZ"]
